export { TaskDialog } from './dialogs/taskdialog/taskdialog.component'
export { EventTemplateDialog } from './dialogs/eventtemplatedialog/eventtemplatedialog.component'
export { EventDialog } from './dialogs/eventdialog/eventdialog.component'
export { UnitDialog } from './dialogs/unitdialog/unitdialog.component'
export { OptionDialog } from './dialogs/optiondialog/optiondialog.component'
export { ErrorDialog } from './dialogs/errordialog/errordialog.component'